# Generated by Django 5.0.6 on 2024-06-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='categıry',
            new_name='category',
        ),
    ]
