# Generated by Django 5.0.6 on 2024-06-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_rename_categıry_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
